name: ESP32 HIL Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hil_teststop:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install pytest pyserial

      - name: Install PlatformIO
        run: |
          pip install platformio

      - name: Build HIL test firmware
        run: |
          pio run -e hil_test

      - name: Flash HIL test firmware
        run: |
          pio run -e hil_test -t upload

      - name: Start Mosquitto MQTT broker
        run: |
          cd "C:\Program Files\mosquitto"
          start "" "mosquitto.exe" -c "mosquitto_local.conf" -v

      - name: Wait for ESP32 reboot
        run: |
          timeout /t 5

      - name: Run HIL tests
        run: |
          pytest -v
